module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.spec.ts',
    '!**/main.ts',
    '!**/*.module.ts',
    '!**/*.dto.ts',
    '!**/*.presenter.ts',
    '!**/*.interface.ts',
    '!**/*.entity.ts',
    '!**/*.model.ts',
    '!**/*.tokens.ts',
    '!**/migrations/**',
    '!**/config/**',
    '!**/common/**',
    '!**/controllers/**',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
};
